import type { CanvasLink, CanvasNode, ComponentMetric, ComponentType } from '../types/graph';
import { forwardFraction } from './components';

/**
 * ArchSim client-side simulation engine.
 *
 * A lightweight steady-state flow model that stands in for the backend DES
 * (see ArchSim/02_Simulation_Engine). Traffic originates at CLIENT nodes,
 * propagates across links (splitting evenly across out-edges, merging at
 * in-edges), and every node applies a type-derived throughput capacity.
 * When arriving load exceeds capacity the surplus queues and a share of it is
 * dropped, driving CPU load, queue depth and error rate.
 *
 * The model is deterministic: same graph in -> same metrics out.
 */

export interface LinkFlow {
  /** Requests per second currently traversing the link. */
  qps: number;
  /** 0..1 saturation of the downstream node this link feeds. */
  saturation: number;
}

export interface SimulationResult {
  metrics: ComponentMetric[];
  linkFlows: Record<string, LinkFlow>;
  /** Peak node saturation across the system (0..1). Handy for headline stats. */
  peakSaturation: number;
  /** Total requests/sec generated by all client sources. */
  totalQps: number;
}

const num = (v: unknown, fallback: number): number =>
  typeof v === 'number' && Number.isFinite(v) ? v : fallback;

/**
 * Steady-state throughput (requests/sec) a node of the given type can service
 * before it starts to queue and drop. Derived from the component's configured
 * specs where possible so the inspector sliders visibly change behaviour.
 */
function nodeCapacity(node: CanvasNode): number {
  const p = node.properties;
  switch (node.type) {
    // Compute
    case 'CLIENT':
      return Infinity; // pure source
    case 'SERVER':
      return num(p.cpu_cores, 4) * 250;
    case 'CONTAINER':
      return num(p.cpu_limit, 2) * 200 * num(p.replicas, 1);
    case 'LAMBDA':
      return num(p.concurrency_limit, 100) * 12;
    case 'VM':
      return num(p.cpu_cores, 2) * 200;

    // Networking
    case 'API_GATEWAY':
      return num(p.rate_limit_rps, 1000);
    case 'LOAD_BALANCER':
      return num(p.max_connections, 10000) * 0.6;
    case 'CDN':
      return 40000;
    case 'DNS':
      return 20000;
    case 'FIREWALL':
      return num(p.max_rules, 100) * 60;

    // Storage
    case 'S3_BUCKET':
      return 5500;
    case 'EBS_VOLUME':
      return num(p.iops, 3000);
    case 'BLOCK_STORAGE':
      return num(p.iops, 1000);

    // Database
    case 'POSTGRESQL':
    case 'MYSQL':
      return num(p.max_connections, 100) * 22;
    case 'MONGODB':
      return num(p.replica_set_members, 3) * 900;
    case 'DYNAMODB':
      return (num(p.read_capacity, 5) + num(p.write_capacity, 5)) * 30;
    case 'CASSANDRA':
      return num(p.num_nodes, 3) * 1200;

    // Cache
    case 'REDIS':
      return 90000;
    case 'MEMCACHED':
      return num(p.max_connections, 1024) * 80;

    // Messaging
    case 'KAFKA':
      return num(p.partitions, 12) * 2500;
    case 'RABBITMQ':
      return 12000;
    case 'SQS':
      return 30000;
    case 'SNS':
      return 30000;

    // Monitoring / Security / K8s: generous pass-through capacities
    case 'PROMETHEUS':
    case 'GRAFANA':
    case 'CLOUDWATCH':
      return 8000;
    case 'WAF':
      return num(p.rate_limit, 2000);
    case 'IAM':
    case 'SECRETS_MANAGER':
      return 6000;
    case 'K8S_CLUSTER':
      return num(p.node_count, 3) * 3000;
    case 'K8S_DEPLOYMENT':
      return num(p.replicas, 3) * 800;
    case 'K8S_SERVICE':
    case 'K8S_INGRESS':
      return 15000;
    default:
      return 5000;
  }
}

/** Baseline idle memory footprint (MB) per component type. */
function baseMemoryMb(node: CanvasNode): number {
  const p = node.properties;
  switch (node.type) {
    case 'SERVER':
      return num(p.memory_gb, 16) * 1024 * 0.15;
    case 'VM':
      return num(p.memory_gb, 4) * 1024 * 0.2;
    case 'CONTAINER':
      return num(p.memory_limit, 512) * 0.25;
    case 'LAMBDA':
      return num(p.memory_mb, 256) * 0.3;
    case 'REDIS':
      return num(p.maxmemory_mb, 256) * 0.2;
    case 'MEMCACHED':
      return num(p.memory_mb, 256) * 0.2;
    default:
      return 128;
  }
}

/** Peak memory (MB) the node can consume, used to scale load-driven RAM. */
function peakMemoryMb(node: CanvasNode): number {
  const p = node.properties;
  switch (node.type) {
    case 'SERVER':
      return num(p.memory_gb, 16) * 1024;
    case 'VM':
      return num(p.memory_gb, 4) * 1024;
    case 'CONTAINER':
      return num(p.memory_limit, 512);
    case 'LAMBDA':
      return num(p.memory_mb, 256);
    case 'REDIS':
      return num(p.maxmemory_mb, 256);
    case 'MEMCACHED':
      return num(p.memory_mb, 256);
    default:
      return 512;
  }
}

const trafficMultiplier: Record<string, number> = {
  STEADY: 1,
  LINEAR: 1.4,
  BURST: 2.2,
};

/**
 * Run the steady-state simulation.
 *
 * @param nodes  Canvas component nodes.
 * @param links  Directed links (source -> target).
 * @param profile Traffic profile name; scales client-generated load.
 */
export function runSimulation(
  nodes: CanvasNode[],
  links: CanvasLink[],
  profile = 'BURST',
): SimulationResult {
  const mult = trafficMultiplier[profile] ?? 1;

  const outLinks = new Map<string, CanvasLink[]>();
  const inLinks = new Map<string, CanvasLink[]>();
  for (const node of nodes) {
    outLinks.set(node.id, []);
    inLinks.set(node.id, []);
  }
  for (const link of links) {
    outLinks.get(link.source)?.push(link);
    inLinks.get(link.target)?.push(link);
  }

  // Generated load at each source (CLIENT) node.
  const generated = new Map<string, number>();
  for (const node of nodes) {
    if (node.type === 'CLIENT') {
      generated.set(node.id, num(node.properties.qps, 100) * mult);
    }
  }

  // Iterative relaxation: link throughput converges as we repeatedly recompute
  // node inflow and re-split it across out-edges (capped at node capacity).
  const linkThroughput = new Map<string, number>();
  for (const link of links) linkThroughput.set(link.id, 0);

  const inflow = new Map<string, number>();
  const ITERATIONS = 12;

  for (let iter = 0; iter < ITERATIONS; iter++) {
    // 1. Node inflow = generated + sum of incoming link throughput.
    for (const node of nodes) {
      let load = generated.get(node.id) ?? 0;
      for (const link of inLinks.get(node.id) ?? []) {
        load += linkThroughput.get(link.id) ?? 0;
      }
      inflow.set(node.id, load);
    }

    // 2. Processed (post-capacity) load splits evenly across out-edges.
    //    Caches/CDNs forward only their misses (forwardFraction), offloading
    //    downstream components.
    for (const node of nodes) {
      const load = inflow.get(node.id) ?? 0;
      const cap = nodeCapacity(node);
      const processed = Math.min(load, cap);
      const sat = cap === Infinity ? 0 : Math.min(load / cap, 1);
      const forwarded = processed * forwardFraction(node, sat);
      const outs = outLinks.get(node.id) ?? [];
      const per = outs.length > 0 ? forwarded / outs.length : 0;
      for (const link of outs) linkThroughput.set(link.id, per);
    }
  }

  // Build per-node metrics from the converged inflow.
  const metrics: ComponentMetric[] = [];
  let peakSaturation = 0;
  let totalQps = 0;

  const saturationById = new Map<string, number>();

  for (const node of nodes) {
    const load = inflow.get(node.id) ?? 0;
    const cap = nodeCapacity(node);
    const saturation = cap === Infinity ? 0 : Math.min(load / cap, 3);
    saturationById.set(node.id, Math.min(saturation, 1));
    peakSaturation = Math.max(peakSaturation, Math.min(saturation, 1));

    if (node.type === 'CLIENT') totalQps += load;

    const cpuUsage = cap === Infinity ? Math.min(load / 50, 100) : Math.min(saturation * 100, 100);
    const overflow = Math.max(0, load - cap);
    // Error rate climbs once queueing begins; capped at ~35%.
    const errorRate = cap === Infinity ? 0 : Math.min(overflow / (cap || 1) * 0.4, 0.35);
    const queueDepth = Math.round(overflow / 10);
    const ramUsageMb = baseMemoryMb(node) + Math.min(saturation, 1) * (peakMemoryMb(node) - baseMemoryMb(node)) * 0.7;

    metrics.push({
      id: node.id,
      cpuUsage,
      ramUsageMb,
      qps: Math.min(load, cap),
      queueDepth,
      errorRate,
    });
  }

  // Link flows carry the downstream node's saturation for colour/animation.
  const linkFlows: Record<string, LinkFlow> = {};
  for (const link of links) {
    linkFlows[link.id] = {
      qps: linkThroughput.get(link.id) ?? 0,
      saturation: saturationById.get(link.target) ?? 0,
    };
  }

  return { metrics, linkFlows, peakSaturation, totalQps };
}

/* ════════════════════ Time-stepped simulation (Milestone 4) ════════════════════ */

export type IncidentType = 'CPU_SPIKE' | 'MEMORY_LEAK' | 'PACKET_LOSS' | 'NODE_KILL';

export interface Incident {
  id: string;
  type: IncidentType;
  /** Node the incident is applied to. PACKET_LOSS degrades all inbound links. */
  targetId: string;
  startFrame: number;
  durationFrames: number;
}

export interface Frame {
  /** Virtual time of this frame in milliseconds. */
  t: number;
  metrics: ComponentMetric[];
  linkFlows: Record<string, LinkFlow>;
  peakSaturation: number;
  totalQps: number;
}

export interface SeriesConfig {
  frames?: number; // number of frames (default 60)
  stepMs?: number; // virtual ms per frame (default 1000 → a 60s run)
  seed?: number;
  trafficMultiplier?: number; // global scale on generated client load (default 1)
}

export const INCIDENT_LABEL: Record<IncidentType, string> = {
  CPU_SPIKE: 'CPU Spike',
  MEMORY_LEAK: 'Memory Leak',
  PACKET_LOSS: 'Packet Loss',
  NODE_KILL: 'Node Kill',
};

/** Deterministic PRNG so a run replays identically. */
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Base traffic multiplier as a function of run progress p ∈ [0,1]. */
function trafficShape(p: number, profile: string): number {
  switch ((profile ?? '').toUpperCase()) {
    case 'LINEAR':
      return 0.4 + 1.3 * p;
    case 'STEADY':
      return 1.0;
    default: // BURST — rolling waves
      return 1.1 + 0.9 * Math.max(0, Math.sin(p * Math.PI * 2.5));
  }
}

/**
 * Run a deterministic time-stepped simulation, returning one Frame per virtual
 * step. Traffic varies over time by profile, and scheduled incidents (chaos)
 * alter node capacity / memory / link loss while active.
 */
export function runSimulationSeries(
  nodes: CanvasNode[],
  links: CanvasLink[],
  profile = 'BURST',
  incidents: Incident[] = [],
  config: SeriesConfig = {},
): Frame[] {
  const N = config.frames ?? 60;
  const stepMs = config.stepMs ?? 1000;
  const rnd = mulberry32(config.seed ?? 42);
  const traffic = config.trafficMultiplier ?? 1;
  const ITER = 12;

  const nodeById = new Map(nodes.map((n) => [n.id, n]));
  const outLinks = new Map<string, CanvasLink[]>();
  const inLinks = new Map<string, CanvasLink[]>();
  for (const node of nodes) {
    outLinks.set(node.id, []);
    inLinks.set(node.id, []);
  }
  for (const link of links) {
    outLinks.get(link.source)?.push(link);
    inLinks.get(link.target)?.push(link);
  }
  const clients = nodes.filter((n) => n.type === 'CLIENT');

  const frames: Frame[] = [];
  for (let i = 0; i < N; i++) {
    const p = N > 1 ? i / (N - 1) : 0;
    const jitter = rnd();
    let m = trafficShape(p, profile) * (0.92 + jitter * 0.16);
    if ((profile ?? '').toUpperCase() === 'BURST' && jitter > 0.9) m += 1.0;

    // Resolve incidents active at this frame.
    const killed = new Set<string>();
    const capMul = new Map<string, number>();
    const linkMul = new Map<string, number>();
    const ramOverride = new Map<string, number>();
    const errorFloor = new Map<string, number>();
    for (const inc of incidents) {
      if (i < inc.startFrame || i >= inc.startFrame + inc.durationFrames) continue;
      const prog = (i - inc.startFrame) / Math.max(1, inc.durationFrames);
      switch (inc.type) {
        case 'NODE_KILL':
          killed.add(inc.targetId);
          break;
        case 'CPU_SPIKE':
          capMul.set(inc.targetId, (capMul.get(inc.targetId) ?? 1) * 0.3);
          break;
        case 'MEMORY_LEAK': {
          const node = nodeById.get(inc.targetId);
          if (node) ramOverride.set(inc.targetId, baseMemoryMb(node) + prog * (peakMemoryMb(node) - baseMemoryMb(node)));
          if (prog > 0.7) capMul.set(inc.targetId, (capMul.get(inc.targetId) ?? 1) * 0.5);
          break;
        }
        case 'PACKET_LOSS':
          for (const l of inLinks.get(inc.targetId) ?? []) linkMul.set(l.id, 0.5);
          errorFloor.set(inc.targetId, Math.max(errorFloor.get(inc.targetId) ?? 0, 0.2));
          break;
      }
    }
    const capOf = (node: CanvasNode) => (killed.has(node.id) ? 0 : nodeCapacity(node) * (capMul.get(node.id) ?? 1));

    const generated = new Map<string, number>();
    for (const c of clients) generated.set(c.id, num(c.properties.qps, 100) * m * traffic);

    // Relax link throughput to steady state for this frame's parameters.
    const linkThroughput = new Map<string, number>();
    for (const l of links) linkThroughput.set(l.id, 0);
    const inflow = new Map<string, number>();
    for (let it = 0; it < ITER; it++) {
      for (const node of nodes) {
        let load = generated.get(node.id) ?? 0;
        for (const l of inLinks.get(node.id) ?? []) load += linkThroughput.get(l.id) ?? 0;
        inflow.set(node.id, load);
      }
      for (const node of nodes) {
        const load = inflow.get(node.id) ?? 0;
        const cap = capOf(node);
        const processed = Math.min(load, cap);
        const sat = cap > 0 && Number.isFinite(cap) ? Math.min(load / cap, 1) : 0;
        const forwarded = processed * forwardFraction(node, sat);
        const outs = outLinks.get(node.id) ?? [];
        const per = outs.length > 0 ? forwarded / outs.length : 0;
        for (const l of outs) linkThroughput.set(l.id, per * (linkMul.get(l.id) ?? 1));
      }
    }

    const metrics: ComponentMetric[] = [];
    const satById = new Map<string, number>();
    let peak = 0;
    let total = 0;
    for (const node of nodes) {
      const load = inflow.get(node.id) ?? 0;
      const cap = nodeCapacity(node) * (capMul.get(node.id) ?? 1);
      const source = cap === Infinity;
      const isKilled = killed.has(node.id);

      let cpu: number, err: number, queue: number, ram: number, qps: number, sat: number;
      if (isKilled) {
        cpu = 0; err = 1; queue = Math.round(load / 10); ram = baseMemoryMb(node); qps = 0; sat = 1;
      } else {
        sat = source ? 0 : Math.min(load / cap, 3);
        cpu = source ? Math.min(load / 50, 100) : Math.min(sat * 100, 100);
        const overflow = Math.max(0, load - cap);
        err = Math.max(source ? 0 : Math.min((overflow / (cap || 1)) * 0.4, 0.35), errorFloor.get(node.id) ?? 0);
        queue = Math.round(overflow / 10);
        ram = ramOverride.get(node.id) ?? baseMemoryMb(node) + Math.min(sat, 1) * (peakMemoryMb(node) - baseMemoryMb(node)) * 0.7;
        qps = source ? load : Math.min(load, cap);
      }
      const clamped = Math.min(isKilled ? 1 : source ? 0 : sat, 1);
      satById.set(node.id, clamped);
      peak = Math.max(peak, clamped);
      if (node.type === 'CLIENT') total += load;
      metrics.push({ id: node.id, cpuUsage: cpu, ramUsageMb: ram, qps, queueDepth: queue, errorRate: err });
    }

    const linkFlows: Record<string, LinkFlow> = {};
    for (const l of links) {
      linkFlows[l.id] = { qps: linkThroughput.get(l.id) ?? 0, saturation: satById.get(l.target) ?? 0 };
    }
    frames.push({ t: i * stepMs, metrics, linkFlows, peakSaturation: peak, totalQps: total });
  }
  return frames;
}

/* ════════════════════ Distributed trace (critical path) ════════════════════ */

export interface TraceSpan {
  id: string;
  label: string;
  type: ComponentType;
  start: number; // ms from request start
  dur: number; // span duration ms
  status: 'ok' | 'warn' | 'crit';
}

export interface Trace {
  spans: TraceSpan[];
  total: number;
}

/** Base processing time (ms) for a healthy node of the given type. */
function procBaseMs(type: ComponentType): number {
  switch (type) {
    case 'CLIENT': return 1;
    case 'REDIS': case 'MEMCACHED': return 1;
    case 'CDN': case 'DNS': case 'LOAD_BALANCER': case 'API_GATEWAY': case 'FIREWALL': case 'WAF': return 2;
    case 'POSTGRESQL': case 'MYSQL': case 'MONGODB': case 'CASSANDRA': case 'DYNAMODB': return 7;
    case 'S3_BUCKET': case 'EBS_VOLUME': case 'BLOCK_STORAGE': return 6;
    case 'LAMBDA': return 5;
    default: return 3;
  }
}

/**
 * Trace a representative request from the first CLIENT along the busiest path
 * at the given frame, accumulating per-hop processing + link latency. Latency
 * grows with node saturation; a downed node produces a timeout span and stops.
 */
export function computeTrace(nodes: CanvasNode[], links: CanvasLink[], frame: Frame): Trace {
  const client = nodes.find((n) => n.type === 'CLIENT');
  if (!client) return { spans: [], total: 0 };

  const nodeById = new Map(nodes.map((n) => [n.id, n]));
  const metricById = new Map(frame.metrics.map((m) => [m.id, m]));
  const out = new Map<string, CanvasLink[]>();
  for (const n of nodes) out.set(n.id, []);
  for (const l of links) out.get(l.source)?.push(l);

  const spans: TraceSpan[] = [];
  const seen = new Set<string>();
  let t = 0;
  let cur: string | undefined = client.id;
  let depth = 0;

  while (cur && !seen.has(cur) && depth < 14) {
    seen.add(cur);
    depth++;
    const node = nodeById.get(cur);
    if (!node) break;
    const m = metricById.get(cur);
    const sat = Math.min((m?.cpuUsage ?? 0) / 100, 1);
    const err = m?.errorRate ?? 0;
    const killed = err >= 1;
    const dur = killed ? 1000 : procBaseMs(node.type) * (1 + sat * sat * 8);
    const status: TraceSpan['status'] = killed || err > 0.1 ? 'crit' : sat >= 0.6 ? 'warn' : 'ok';
    spans.push({ id: node.id, label: node.label, type: node.type, start: t, dur, status });
    t += dur;
    if (killed) break;

    const outs: CanvasLink[] = out.get(cur) ?? [];
    if (outs.length === 0) break;
    let best: CanvasLink = outs[0];
    let bestQ = -1;
    for (const l of outs) {
      const q = frame.linkFlows[l.id]?.qps ?? 0;
      if (q > bestQ) { bestQ = q; best = l; }
    }
    t += best.properties.latencyMs ?? 1; // link transit
    cur = best.target;
  }

  return { spans, total: t };
}
